name = "Cartan"
uuid = "ab205724-bc94-4f9d-9de2-3802b5d24b63"
authors = ["Omar Alsheikh"]
version = "0.1.0"

[compat]
SafeTestsets = "0.1.0"
julia = "1.11"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
