name = "Cartan"
uuid = "615a691c-4fc5-44f7-931d-c95ef2459ac1"
authors = ["Omar Alsheikh"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
