function _dla(string::Unsigned, iter, Q::Integer)
    strings = com.(string, iter, Q)
    return filter!(x -> !x.second, strings) .|> (x -> x.first)
end

function serial_dla(paulis::PauliList)
    finalind = length(paulis)
    initialind = 1
    algebra = copy(paulis)
    while true
        for i in eachindex(algebra)[end:-1:initialind]
            newpaulis = _dla(algebra[i], view(algebra, 1:i-1), paulis.qubits)
            union!(algebra, newpaulis)
        end
        finalind == length(algebra) && return algebra
        initialind = finalind + 1
        finalind = length(algebra)
    end
end

function parallel_dla(paulis::PauliList)
    finalind = length(paulis)
    initialind = 1
    algebra = copy(paulis)
    while true
        for i in eachindex(algebra)[end:-1:initialind]
            iter = @view algebra[i-1:-1:1]
            chunks = Iterators.partition(iter, max(1, length(iter) ÷ Threads.nthreads()))
            tasks = map(chunks) do chunk
                Threads.@spawn _dla(algebra[i], chunk, paulis.qubits)
            end
            union!(algebra, fetch.(tasks)...)
        end
        finalind == length(algebra) && return algebra
        initialind = finalind + 1
        finalind = length(algebra)
    end
end

"""
    dla(paulis::PauliList)

Compute the dynamical Lie algebra generated by `paulis`.

Recursively compute commutators until closure is reached.
"""
const dla = isone(Threads.nthreads()) ? serial_dla : parallel_dla

"""
    subalgfind(paulis::PauliList)

Find a maximal Abelian subalgebra (Cartan subalgebra) inside `paulis`. The routine
sorts the input Pauli strings by increasing Pauli weight and greedily adds commuting
elements to the subalgebra.
"""
function subalgfind(paulis::PauliList)
    sortedstrings = sort(paulis, by=x -> counti(x, paulis.qubits), rev=true)
    subalgebra = sortedstrings[1:1]
    for g in sortedstrings[2:end]
        for h in subalgebra
            com(g, h, paulis.qubits).second || break
            h == subalgebra[end] && (push!(subalgebra, g); break)
        end
    end
    return PauliList(subalgebra, paulis.qubits, iscopy=false)
end

@doc raw"""
    cartandecomp(paulis::PauliList, involution::Function)

Compute a Cartan decomposition of the Lie algebra ``\mathfrak{g}`` basis `paulis` using the
`involution` `θ`.

Find the Cartan decomposition ``\mathfrak{g} = \mathfrak{k} \oplus \mathfrak{m}`` such that
``\mathfrak{k}`` (``\mathfrak{m}``) is the +1 (-1) eigenspace of `θ`. Find a Cartan
subalgebra ``\mathfrak{h} \subseteq \mathfrak{m}``.

See also [`involutionlessdecomp`](@ref).
"""
function cartandecomp(paulis::PauliList, involution::Function)
    inds = involution(paulis)
    k = PauliList(paulis[inds], paulis.qubits, iscopy=false)
    m = PauliList(paulis[.!inds], paulis.qubits, iscopy=false)
    return Dict(:k => k, :m => m, :h => subalgfind(m))
end
