function _dla(string::Pair{<:Unsigned,<:Integer}, iter, Q::Integer)
    strings = Pair.(com.(string.first, first.(iter), Q), string.second .* last.(iter))
    return filter!(x -> !x.first.second, strings) .|> (x -> Pair(x.first.first, x.second))
end

function serial_involutionlessdecomp(paulis::PauliList)
    finalind = length(paulis)
    initialind = 1
    algebra = Pair.(paulis, Int8(-1))
    contradiction = false
    while !contradiction
        for i in eachindex(algebra)[end:-1:initialind]
            newpaulis = _dla(algebra[i], view(algebra, i-1:-1:1), paulis.qubits)
            union!(algebra, newpaulis)
            length(algebra) == length(unique!(x -> x.first, algebra)) ||
                (contradiction = true)
        end
        if finalind == length(algebra)
            alg = PauliList(first.(algebra), paulis.qubits, iscopy=false)
            contradiction &&
                return Dict(:g => alg, :h => subalgfind(alg), :k => nothing, :m => nothing)
            m = filter(x -> x.second == -1, algebra)
            m = PauliList(first.(m), paulis.qubits, iscopy=false)
            k = filter(x -> x.second == 1, algebra)
            k = PauliList(first.(k), paulis.qubits, iscopy=false)
            return Dict(:g => alg, :k => k, :m => m, :h => subalgfind(m))
        end
        initialind = finalind + 1
        finalind = length(algebra)
        contradiction &&
            (algebra = PauliList(first.(algebra), paulis.qubits, iscopy=false); break)
    end

    while true
        for i in eachindex(algebra)[end:-1:initialind]
            newpaulis = _dla(algebra[i], view(algebra, 1:i-1), paulis.qubits)
            union!(algebra, newpaulis)
        end

        finalind == length(algebra) && return Dict(
            :g => algebra,
            :h => subalgfind(algebra),
            :k => nothing,
            :m => nothing,
        )

        initialind = finalind + 1
        finalind = length(algebra)
    end
end

function parallel_involutionlessdecomp(paulis::PauliList)
    finalind = length(paulis)
    initialind = 1
    algebra = Pair.(paulis, Int8(-1))
    contradiction = false
    while !contradiction
        for i in eachindex(algebra)[end:-1:initialind]
            iter = @view algebra[i-1:-1:1]
            chunks = Iterators.partition(iter, max(1, length(iter) ÷ Threads.nthreads()))
            tasks = map(chunks) do chunk
                Threads.@spawn _dla(algebra[i], chunk, paulis.qubits)
            end
            union!(algebra, fetch.(tasks)...)
            length(algebra) == length(unique!(x -> x.first, algebra)) ||
                (contradiction = true)
        end
        if finalind == length(algebra)
            alg = PauliList(first.(algebra), paulis.qubits, iscopy=false)
            contradiction &&
                return Dict(:g => alg, :h => subalgfind(alg), :k => nothing, :m => nothing)
            m = filter(x -> x.second == -1, algebra)
            m = PauliList(first.(m), paulis.qubits, iscopy=false)
            k = filter(x -> x.second == 1, algebra)
            k = PauliList(first.(k), paulis.qubits, iscopy=false)
            return Dict(:g => alg, :k => k, :m => m, :h => subalgfind(m))
        end
        initialind = finalind + 1
        finalind = length(algebra)
        contradiction &&
            (algebra = PauliList(first.(algebra), paulis.qubits, iscopy=false); break)
    end

    while true
        for i in eachindex(algebra)[end:-1:initialind]
            iter = @view algebra[i-1:-1:1]
            chunks = Iterators.partition(iter, max(1, length(iter) ÷ Threads.nthreads()))
            tasks = map(chunks) do chunk
                Threads.@spawn _dla(algebra[i], chunk, paulis.qubits)
            end
            union!(algebra, fetch.(tasks)...)
        end

        finalind == length(algebra) && return Dict(
            :g => algebra,
            :h => subalgfind(algebra),
            :k => nothing,
            :m => nothing,
        )

        initialind = finalind + 1
        finalind = length(algebra)
    end
end

@doc raw"""
    involutionlessdecomp(paulis::PauliList)

Compute an involutionless Cartan decomposition of the algebra generated by `paulis`.

Build the dynamical Lie algebra ``\mathfrak{g}`` generated by `paulis` while tracking a sign
bit for involution consistency. Return a `Dict` containing the generated algebra and the
subspaces ``\mathfrak{k}`` and ``\mathfrak{m}`` associated with the Cartan decomposition
that keeps `paulis` in ``\mathfrak{m}``. Return a Cartan subalgebra ``\mathfrak{h} \subseteq
\mathfrak{m}``. If no such decomposition exists, return ``\mathfrak{g}`` and ``\mathfrak{h}
\subseteq \mathfrak{g}``.

See also [`dla`](@ref), [`cartandecomp`](@ref), [`subalgfind`](@ref).
"""
const involutionlessdecomp =
    isone(Threads.nthreads()) ? serial_involutionlessdecomp : parallel_involutionlessdecomp